using Microsoft.EntityFrameworkCore;

namespace FilmsRazorPages.Models
{
    public class ClassContext : DbContext
    {
        public DbSet<Film> Films { get; set; }
        public ClassContext(DbContextOptions<ClassContext> options)
           : base(options)
        {
            if (Database.EnsureCreated())
            {
                Films?.Add(new Film { Name="Forrest Gump", Genre="Comedie dramatique", Realisateur ="Robert Zemeckis", Anne ="1994", Description="Quelques décennies d'histoire américaine, des années 1940 à la fin du XXème siècle, à travers le regard et l'étrange odyssée d'un homme simple et pur, Forrest Gump.", Poster="/Posters/ForestGamp.jpg" });
                Films?.Add(new Film { Name="La Liste de Schindler", Genre="Drame historique epique", Realisateur ="Steven Spielberg", Anne ="1994", Description="Evocation des années de guerre d'Oskar Schindler, fils d'industriel d'origine autrichienne rentré à Cracovie en 1939 avec les troupes allemandes. Il va, tout au long de la guerre, protéger des juifs en les faisant travailler dans sa fabrique et en 1944 sauver huit cents hommes et trois cents femmes du camp d'extermination de Auschwitz-Birkenau.", Poster="/Posters/ShindlerList.jpg" });
                Films?.Add(new Film { Name="Le Pianiste", Genre="Drame historique", Realisateur ="Roman Polanski", Anne ="2002", Description="Durant la Seconde Guerre mondiale, Wladyslaw Szpilman, un célèbre pianiste juif polonais, échappe à la déportation mais se retrouve parqué dans le ghetto de Varsovie dont il partage les souffrances, les humiliations et les luttes héroïques. Il parvient à s'en échapper et se réfugie dans les ruines de la capitale. Un officier allemand, qui apprécie sa musique, l'aide et lui permet de survivre.", Poster="/Posters/Pianist.jpg" });
                Films?.Add(new Film { Name="Le Parrain", Genre="Drame", Realisateur ="Francis Ford Coppola", Anne ="1972", Description="En 1945, à New York, les Corleone sont une des cinq familles de la mafia. Don Vito Corleone, de cette famille, marie sa fille à un bookmaker. Sollozzo, de la famille Tattaglia, propose à Don Vito une association dans le trafic de drogue, mais celui-ci refuse. Sonny, un de ses fils, y est quant à lui favorable. Afin de traiter avec Sonny, Sollozzo tente de faire tuer Don Vito, mais celui-ci en réchappe.", Poster="/Posters/Godfather.jpg" });
                Films?.Add(new Film { Name="Les Évadés", Genre="Drame", Realisateur =" Frank Darabont", Anne ="1995", Description="En 1947, Andy Dufresne, un jeune banquier, est condamné à la prison à vie pour le meurtre de sa femme et de son amant. Ayant beau clamer son innocence, il est emprisonné à Shawshank, le pénitencier le plus sévère de l'Etat du Maine. Il y fait la rencontre de Red, détenu depuis vingt ans. Commence alors une grande histoire d'amitié entre les deux hommes...", Poster="/Posters/las_evades.jpg" });
                Films?.Add(new Film { Name="La Ligne verte", Genre="Drame", Realisateur ="Frank Darabont", Anne ="1999", Description="Paul Edgecomb, Gardien-chef du pénitencier de Cold Mountain en 1935, était chargé de veiller au bon déroulement des exécutions capitales. Parmi les prisonniers se trouvait un colosse du nom de John Coffey...", Poster="/Posters/LigneVerte.jpg" });
                Films?.Add(new Film { Name="Green book: sur les routes du Sud", Genre="Comedie dramatique", Realisateur ="Peter Farrelly", Anne ="2018", Description="L'histoire se déroule aux États-Unis en 1962. Frank Vallelonga, surnommé « Tony la tchatche », un videur italo-américain de New York, cherche un emploi après la fermeture pour rénovation du Copacabana, la boîte de nuit où il travaillait. Il est invité à un entretien par le docteur Don Shirley, un excentrique pianiste noir d'origine jamaïcaine, qui cherche un chauffeur pour une tournée de huit semaines à travers le Midwest et le Sud profond.", Poster="/Posters/GreenBook.jpg" });
                Films?.Add(new Film { Name="La Matrice", Genre="Science-fiction", Realisateur ="Les Wachowski", Anne ="1999", Description="Thomas A. Anderson , un jeune informaticien connu dans le monde du hacking sous le pseudonyme de Neo , est contacté via son ordinateur par ce qu’il pense être un groupe de hackers. Ils lui font découvrir que le monde dans lequel il vit n’est qu’un monde virtuel appelé la Matrice, à l'intérieur duquel les êtres humains sont gardés inconsciemment sous contrôle.", Poster="/Posters/Matrix.jpg" });
                Films?.Add(new Film { Name="Avatar", Genre="Science-fiction", Realisateur ="James Cameron", Anne ="2009", Description="In the year 2154, a human colony has been established on a distant planet called Pandora. The humans are hunting for a rare mineral that could solve the ecological crisis on Earth. However, their plans are thwarted by an indigenous race called the Na'vi, whose village is resting right on top of the rare ore they need. To solve this problem, Col. Quaritch sends ex-Marine Jake Sully out into the wild piloting an Avatar- a remote control alien body that will allow Jake to breath the air on Pandora- to gain the Na'vi's trust and get them to relocate.", Poster="/Posters/Avatar.jpg" });
                Films?.Add(new Film { Name="Le cinquieme element", Genre="Science-fiction", Realisateur ="Luc Besson", Anne ="1997", Description="Égypte, 1914. Un groupe de Mondo-shawans débarque sur Terre afin de récupérer quatre pierres représentant les quatre éléments de la vie, afin de les soustraire à l'arrivée imminente de la Première Guerre mondiale. Ils promettent de les rapporter dans 300 ans, lorsque le Mal reviendra, afin d'établir une paix durable. Mais à leur retour, trois siècles plus tard, leur vaisseau est détruit et les pierres disparaissent mystérieusement.", Poster="/Posters/5element.jpg" });
                SaveChanges();
            }
        }

    }
}
